version: '3.9'

services:

  kafka:
    image: lensesio/fast-data-dev:2.2
    container_name: test_kafka
    restart: unless-stopped
    ports:
      - "2181:2181" # zookeeper
      - "9092:9092" # kafka
      - "3030:3030" # ui
    environment:
      - ADV_HOST=127.0.0.1
      - SAMPLEDATA=0 # Do not create topics with sample avro and json records
